# Generated by Django 4.2.7 on 2023-12-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pic_book", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetemplate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="picbook",
            name="author",
            field=models.ManyToManyField(to="users.author"),
        ),
        migrations.AddField(
            model_name="picbook",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="picbook",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="picbook",
            name="voice_template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.voicetemplate"),
        ),
        migrations.AddField(
            model_name="paragraphvoicefile",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="paragraphvoicefile",
            name="voice_template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.voicetemplate"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="book_page",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.bookpage"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="illustration",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.illustrationfile"
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="knowledge_point",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.knowledgepoint"
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="knowledgevoicefile",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="knowledgevoicefile",
            name="voice_template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.voicetemplate"),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.illustrationfile"
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="illustrationfile",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="chapter",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="bookseries",
            name="pic_books",
            field=models.ManyToManyField(to="pic_book.picbook"),
        ),
        migrations.AddField(
            model_name="bookseries",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="bookseries",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="chapter",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.chapter"),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="layout",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.layouttemplate"
            ),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="pic_book",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook"),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="paragraphvoicefile",
            unique_together={("para_content_uniq", "voice_template")},
        ),
        migrations.AlterUniqueTogether(
            name="paragraph",
            unique_together={("book_page", "para_content_uniq")},
        ),
        migrations.AlterUniqueTogether(
            name="knowledgevoicefile",
            unique_together={("knowledge_uniq", "voice_template")},
        ),
        migrations.AlterUniqueTogether(
            name="knowledgepoint",
            unique_together={("knowledge_uniq", "pic_style", "language")},
        ),
    ]
