# Generated by Django 4.2.7 on 2024-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["seq"]},
        ),
        migrations.AlterField(
            model_name="bookpage",
            name="seq",
            field=models.IntegerField(db_index=True, default=1, help_text="当前为章节内部排序", verbose_name="页码顺序"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to="", verbose_name="插图"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="illustration",
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to="", verbose_name="插图"),
        ),
        migrations.DeleteModel(
            name="IllustrationFile",
        ),
    ]
