# Generated by Django 4.2.7 on 2023-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picbook",
            name="state",
            field=models.SmallIntegerField(
                choices=[(1, "online"), (-1, "offline"), (0, "prepare")], default=0, verbose_name="绘本状态"
            ),
        ),
        migrations.AddField(
            model_name="picbook",
            name="voice_state",
            field=models.SmallIntegerField(
                choices=[(1, "done"), (0, "prepare"), (2, "process"), (-1, "error")], default=0, verbose_name="绘本语音状态"
            ),
        ),
        migrations.AddField(
            model_name="voicetemplate",
            name="dataset",
            field=models.CharField(default="ljspeech", max_length=20, verbose_name="tts模型数据集"),
        ),
        migrations.AddField(
            model_name="voicetemplate",
            name="model_name",
            field=models.CharField(default="xtts_v1", max_length=20, verbose_name="模型名称"),
        ),
        migrations.AddField(
            model_name="voicetemplate",
            name="vocoder",
            field=models.CharField(default="hifigan_v2", max_length=20, verbose_name="使用tts模型"),
        ),
        migrations.AlterField(
            model_name="voicetemplate",
            name="language",
            field=models.CharField(
                default="en_US", help_text="language-ios_code, coqui保存路径", max_length=16, verbose_name="语言"
            ),
        ),
        migrations.AlterField(
            model_name="voicetemplate",
            name="speaker",
            field=models.CharField(blank=True, max_length=50, verbose_name="语音编码"),
        ),
        migrations.AlterField(
            model_name="voicetemplate",
            name="tts_model",
            field=models.CharField(
                default="coqui-ai",
                help_text="开源TTS算法, coqui-ai, SpeechT5-microsoft",
                max_length=20,
                verbose_name="tts模型",
            ),
        ),
    ]
