# Generated by Django 4.2.7 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0002_alter_chapter_options_alter_bookpage_seq_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="knowledgepoint",
            unique_together={("knowledge_uniq", "language")},
        ),
        migrations.RemoveField(
            model_name="paragraph",
            name="knowledge_point",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="knowledge",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="知识点"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="knowledge_uniq",
            field=models.CharField(
                blank=True, help_text="对知识点前后去空格，转小写，MD5加密", max_length=64, null=True, verbose_name="知识点MD5"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="grade",
            field=models.CharField(
                choices=[
                    ("age1-preschool", "学前1岁"),
                    ("age2-preschool", "学前2岁"),
                    ("age3-preschool", "学前3岁"),
                    ("age4-preschool", "学前4岁"),
                    ("age5-preschool", "学前5岁"),
                    ("kindergarten", "幼儿园"),
                    ("grade1-primary", "小学一年级"),
                    ("grade2-primary", "小学二年级"),
                    ("grade3-primary", "小学三年级"),
                    ("grade4-primary", "小学四年级"),
                    ("grade5-primary", "小学五年级"),
                    ("grade6-primary", "小学六年级"),
                    ("grade7-middle", "初中一年级"),
                    ("grade8-middle", "初中二年级"),
                    ("grade9-middle", "初中三年级"),
                    ("grade10-high", "高中一年级"),
                    ("grade11-high", "高中二年级"),
                    ("grade12-high", "高中三年级"),
                    ("freshman-university", "大学一年级"),
                    ("sophomore-university", "大学二年级"),
                    ("junior-university", "大学三年级"),
                    ("senior-university", "大学四年级"),
                ],
                default="1t2-preschool",
                max_length=30,
                verbose_name="默认年级",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to="", verbose_name="默认插图"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="language_level",
            field=models.CharField(
                choices=[
                    ("A1", "入门级，可以做简单的互动与交流"),
                    ("A2", "基础级，能理解并使用熟悉的日常表达法，基本词汇以求满足具体的需求"),
                    ("B1", "进阶级，能理解大部分日常生活中常用句子和表达法"),
                    ("B2", "高阶级，能在与以目标语言为母语的对象做互动时保持一定流畅度"),
                    ("C1", "流利运用级，在社交上、学术上及专业的场合中，皆能灵活的有效地运用语言资源"),
                    ("C2", "精通级，能流利、准确、并即兴的表达自己的意见，并且在较为复杂的情况下亦能有效地表达或区别出言外之意"),
                ],
                default="A1",
                max_length=16,
                verbose_name="默认语言级别",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="phase",
            field=models.CharField(
                choices=[
                    ("preschool", "学前班"),
                    ("kindergarten", "幼儿园"),
                    ("primary", "小学"),
                    ("middle", "初中"),
                    ("high", "高中"),
                    ("university", "大学"),
                ],
                default="preschool",
                max_length=20,
                verbose_name="默认学段",
            ),
        ),
        migrations.RemoveField(
            model_name="knowledgepoint",
            name="pic_style",
        ),
    ]
