# Generated by Django 4.2.7 on 2023-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0002_picbook_state_picbook_voice_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookseries",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chaptertemplate",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="illustrationfile",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="knowledgevoicefile",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paragraphvoicefile",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="picbook",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="voicetemplate",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
