# Generated by Django 4.2.7 on 2023-12-20 14:59

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("pic_book", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="pic_book",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookseries",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.illustrationfile"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="layouttemplate",
            name="background_color",
            field=models.CharField(default="#FFFFFF", max_length=16, verbose_name="背景颜色"),
        ),
        migrations.AlterField(
            model_name="layouttemplate",
            name="background_img",
            field=models.ImageField(blank=True, null=True, upload_to="pic_books/background_img/", verbose_name="背景图面"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="book_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="paragraphs", to="pic_book.bookpage"
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="illustration",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.illustrationfile"
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="knowledge_point",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.knowledgepoint"
            ),
        ),
        migrations.AlterField(
            model_name="picbook",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
