# Generated by Django 4.2.7 on 2023-12-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0003_chapter_pic_book_alter_bookseries_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="chapter",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="pic_book.chapter"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paragraph",
            name="pic_book",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook"),
            preserve_default=False,
        ),
    ]
