# Generated by Django 4.2.7 on 2024-01-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0003_alter_knowledgepoint_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paragraphvoicefile",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="picbook",
            name="voice_state",
        ),
        migrations.AddField(
            model_name="paragraphvoicefile",
            name="pic_book",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="picbook",
            name="voice_template",
        ),
        migrations.AlterUniqueTogether(
            name="paragraphvoicefile",
            unique_together={("pic_book", "para_content_uniq", "voice_template")},
        ),
        migrations.CreateModel(
            name="PicBookVoiceTemplateRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "voice_state",
                    models.SmallIntegerField(
                        choices=[(1, "done"), (0, "prepare"), (2, "process"), (-1, "error")],
                        default=0,
                        verbose_name="绘本语音状态",
                    ),
                ),
                ("seq", models.SmallIntegerField(default=1, help_text="排序最小的为默认", verbose_name="排序")),
                ("ctime", models.DateTimeField(auto_now_add=True)),
                ("utime", models.DateTimeField(auto_now=True)),
                ("pic_book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook")),
                (
                    "voice_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.voicetemplate"),
                ),
            ],
            options={
                "db_table": "mlnbook_pic_book_voice_template_book_relation",
                "ordering": ["seq"],
            },
        ),
        migrations.AddField(
            model_name="picbook",
            name="voice_template",
            field=models.ManyToManyField(
                blank=True, through="pic_book.PicBookVoiceTemplateRelation", to="pic_book.voicetemplate"
            ),
        ),
    ]
