# Generated by Django 4.2.7 on 2023-12-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0004_paragraph_chapter_paragraph_pic_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookpage",
            name="page_num",
        ),
        migrations.AddField(
            model_name="bookpage",
            name="seq",
            field=models.IntegerField(default=1, verbose_name="页码顺序"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.chapter"
            ),
        ),
    ]
