# Generated by Django 4.2.7 on 2024-01-29 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pic_book", "0005_remove_voicetemplate_dataset_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paragraph",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chapter",
            name="set_group",
            field=models.BooleanField(default=False, verbose_name="设为分组"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="para_content_uniq",
            field=models.CharField(blank=True, help_text="content文本MD5加密", max_length=64, verbose_name="段落内容唯一标识"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="seq",
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name="章节内排序"),
        ),
        migrations.AlterField(
            model_name="paragraphvoicefile",
            name="voice_file",
            field=models.FileField(blank=True, null=True, upload_to="pic_book/voice_file", verbose_name="语音文件"),
        ),
        migrations.AlterField(
            model_name="voicetemplate",
            name="tts_model",
            field=models.CharField(
                default="azure-api",
                help_text="开源TTS算法 coqui-ai, 微软语音服务 azure-api; 人工 manual",
                max_length=20,
                verbose_name="tts模型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paragraph",
            unique_together={("chapter", "para_content_uniq")},
        ),
        migrations.AlterUniqueTogether(
            name="picbookvoicetemplaterelation",
            unique_together={("pic_book", "voice_template")},
        ),
        migrations.CreateModel(
            name="Typeset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "c_type",
                    models.CharField(
                        default="norm", help_text="norm 标准化的； custom 人工定制的", max_length=15, verbose_name="排版类型"
                    ),
                ),
                (
                    "setting",
                    models.JSONField(
                        blank=True,
                        help_text="结构为 [[layoutID, layoutID, layoutID], [layoutID, layoutID]]; 每行为一章内容",
                        null=True,
                        verbose_name="设定",
                    ),
                ),
                ("seq", models.IntegerField(db_index=True, default=1, help_text="当前为章节内部排序", verbose_name="页码顺序")),
                ("is_default", models.BooleanField(default=False)),
                ("ctime", models.DateTimeField(auto_now_add=True)),
                ("utime", models.DateTimeField(auto_now=True)),
                ("pic_book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "mlnbook_pic_book_typeset",
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="ChapterTypeset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "setting",
                    models.JSONField(
                        blank=True,
                        help_text="结构为 [[layoutID, layoutID, layoutID], [layoutID, layoutID]]; 每行为一章内容",
                        null=True,
                        verbose_name="设定",
                    ),
                ),
                ("ctime", models.DateTimeField(auto_now_add=True)),
                ("utime", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.chapter"
                    ),
                ),
                (
                    "pic_book",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pic_book.picbook"
                    ),
                ),
                ("typeset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pic_book.typeset")),
            ],
            options={
                "db_table": "mlnbook_pic_book_custom_chapter_typeset",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="paragraph",
            name="book_page",
        ),
        migrations.DeleteModel(
            name="BookPage",
        ),
    ]
