# Generated by Django 4.2.7 on 2024-02-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0006_alter_paragraph_unique_together_chapter_set_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgepoint",
            name="small_illustration",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="pic_books/small_illustration/", verbose_name="缩略插图"
            ),
        ),
        migrations.AlterField(
            model_name="chaptertypeset",
            name="setting",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="结构为 [layoutID, layoutID, layoutID]; 按布局填充内容",
                null=True,
                verbose_name="设定",
            ),
        ),
        migrations.AlterField(
            model_name="chaptertypeset",
            name="typeset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="chapter_typesets", to="pic_book.typeset"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="pic_books/illustration/", verbose_name="默认插图"
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="illustration",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="pic_books/illustration/", verbose_name="插图"
            ),
        ),
        migrations.AlterField(
            model_name="picbook",
            name="cover_img",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="pic_books/cover_img/", verbose_name="封面图"
            ),
        ),
        migrations.AlterField(
            model_name="typeset",
            name="setting",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="结构为 [layoutID, layoutID, layoutID]; 按布局填充内容",
                null=True,
                verbose_name="设定",
            ),
        ),
    ]
