# Generated by Django 4.2.7 on 2024-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0007_knowledgepoint_small_illustration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="small_illustration",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="pic_books/small_illustration/", verbose_name="插图"
            ),
        ),
    ]
