# Generated by Django 4.2.7 on 2024-02-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0008_paragraph_small_illustration"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="aigc_payload",
            field=models.JSONField(blank=True, help_text="参考stable diffusion API", null=True, verbose_name="SD提交json"),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="aigc_prompt",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="SD正向提示词"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="illustration",
            field=models.ImageField(blank=True, null=True, upload_to="pic_books/illustration/", verbose_name="默认插图"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="small_illustration",
            field=models.ImageField(
                blank=True, null=True, upload_to="pic_books/small_illustration/", verbose_name="缩略插图"
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="illustration",
            field=models.ImageField(blank=True, null=True, upload_to="pic_books/illustration/", verbose_name="插图"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="small_illustration",
            field=models.ImageField(
                blank=True, null=True, upload_to="pic_books/small_illustration/", verbose_name="插图"
            ),
        ),
    ]
