# Generated by Django 4.2.7 on 2024-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pic_book", "0009_paragraph_aigc_payload_paragraph_aigc_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="prompt_template",
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="提示词模板"),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="aigc_payload",
            field=models.JSONField(
                blank=True, help_text="参考stable diffusion API", null=True, verbose_name="生成式提交的json"
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="aigc_prompt",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="生成式提示词"),
        ),
    ]
