# Generated by Django 4.2.7 on 2023-12-19 13:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of User")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("phone", models.CharField(blank=True, max_length=16, verbose_name="联系方式")),
                ("email", models.CharField(blank=True, max_length=50, verbose_name="email")),
                ("id_card", models.CharField(blank=True, max_length=20, verbose_name="身份信息")),
                ("description", models.TextField(blank=True, verbose_name="介绍信息")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en_US", "英语"),
                            ("zh_CN", "简体中文"),
                            ("fr_FR", "法语"),
                            ("es_ES", "西班牙语"),
                            ("ar_AE", "阿拉伯语"),
                            ("ru_RU", "俄语"),
                            ("pt_BR", "葡萄牙语"),
                            ("ja_JP", "日语"),
                            ("de_DE", "德语"),
                            ("ko_KR", "韩语"),
                            ("in_ID", "印尼语"),
                            ("ms_MY", "马来语"),
                            ("th_TH", "泰语"),
                            ("hi_IN", "北印度语"),
                            ("tr_TR", "土耳其语"),
                            ("it_IT", "意大利语"),
                            ("cs_CZ", "捷克语"),
                            ("da_DK", "丹麦语"),
                            ("nl_NL", "荷兰语"),
                            ("no_NO", "挪威语"),
                            ("pl_PL", "波兰语"),
                            ("ro_RO", "罗马尼亚语"),
                            ("sv_SE", "瑞典语"),
                            ("tl_PH", "他加禄语-菲律宾"),
                        ],
                        default="zh_CN",
                        max_length=16,
                        verbose_name="母语",
                    ),
                ),
                (
                    "c_type",
                    models.CharField(
                        default="staff",
                        help_text="certification 入驻认证，staff 平台内部组员，public 历史公开公共资源",
                        max_length=16,
                        verbose_name="作者类型",
                    ),
                ),
                ("ctime", models.DateTimeField(auto_now_add=True)),
                ("utime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mlnbook_user_authors",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nick_name", models.CharField(blank=True, max_length=50, verbose_name="别名")),
                (
                    "native_language",
                    models.CharField(
                        choices=[
                            ("en_US", "英语"),
                            ("zh_CN", "简体中文"),
                            ("fr_FR", "法语"),
                            ("es_ES", "西班牙语"),
                            ("ar_AE", "阿拉伯语"),
                            ("ru_RU", "俄语"),
                            ("pt_BR", "葡萄牙语"),
                            ("ja_JP", "日语"),
                            ("de_DE", "德语"),
                            ("ko_KR", "韩语"),
                            ("in_ID", "印尼语"),
                            ("ms_MY", "马来语"),
                            ("th_TH", "泰语"),
                            ("hi_IN", "北印度语"),
                            ("tr_TR", "土耳其语"),
                            ("it_IT", "意大利语"),
                            ("cs_CZ", "捷克语"),
                            ("da_DK", "丹麦语"),
                            ("nl_NL", "荷兰语"),
                            ("no_NO", "挪威语"),
                            ("pl_PL", "波兰语"),
                            ("ro_RO", "罗马尼亚语"),
                            ("sv_SE", "瑞典语"),
                            ("tl_PH", "他加禄语-菲律宾"),
                        ],
                        default="zh_CN",
                        max_length=16,
                        verbose_name="母语",
                    ),
                ),
                (
                    "learn_language",
                    models.CharField(
                        choices=[
                            ("en_US", "英语"),
                            ("zh_CN", "简体中文"),
                            ("fr_FR", "法语"),
                            ("es_ES", "西班牙语"),
                            ("ar_AE", "阿拉伯语"),
                            ("ru_RU", "俄语"),
                            ("pt_BR", "葡萄牙语"),
                            ("ja_JP", "日语"),
                            ("de_DE", "德语"),
                            ("ko_KR", "韩语"),
                            ("in_ID", "印尼语"),
                            ("ms_MY", "马来语"),
                            ("th_TH", "泰语"),
                            ("hi_IN", "北印度语"),
                            ("tr_TR", "土耳其语"),
                            ("it_IT", "意大利语"),
                            ("cs_CZ", "捷克语"),
                            ("da_DK", "丹麦语"),
                            ("nl_NL", "荷兰语"),
                            ("no_NO", "挪威语"),
                            ("pl_PL", "波兰语"),
                            ("ro_RO", "罗马尼亚语"),
                            ("sv_SE", "瑞典语"),
                            ("tl_PH", "他加禄语-菲律宾"),
                        ],
                        default="en_US",
                        max_length=16,
                        verbose_name="学习语言",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("preschool", "学前班"),
                            ("kindergarten", "幼儿园"),
                            ("primary", "小学"),
                            ("middle", "初中"),
                            ("high", "高中"),
                            ("university", "大学"),
                        ],
                        default="preschool",
                        max_length=20,
                        verbose_name="学段",
                    ),
                ),
                (
                    "child_gender",
                    models.CharField(
                        default="M", help_text="M male, F female, U Unknown", max_length=16, verbose_name="孩子性别"
                    ),
                ),
                ("child_age", models.IntegerField(default=2, verbose_name="孩子年龄")),
                ("valid_author", models.BooleanField(default=False, verbose_name="认证作者")),
                ("ctime", models.DateTimeField(auto_now_add=True)),
                ("utime", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="平台作者认证，生成author对象关联",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.author",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "mlnbook_user_profile",
            },
        ),
    ]
