# Generated by Django 4.2.7 on 2023-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_author_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ctime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
